var employeeId = 1;
console.log("Employee type is:" + typeof employeeId);
var employeeName;
employeeName = "Divya";
console.log("EemployeeName type:" + typeof employeeName);
var isEmployee = true;
console.log("isEmployee type:" + typeof isEmployee);
var nullValues = null;
console.log("nullValues type:" + typeof nullValues);
var undefinedValue = undefined;
console.log("undefinedValue type:" + typeof undefinedValue);
var someValue = 1;
console.log("someValue of type:" + typeof someValue);
someValue = "Djspy";
console.log("someValue of type:" + typeof someValue);
someValue = true;
console.log("someValue of type:" + typeof someValue);
var randomNames = [];
randomNames = ["D", "j", "s", "p", "y"];
console.log(randomNames);
var randomNumbers = [];
randomNumbers = [1, 2, 3, 4, 5];
console.log(randomNumbers);
var mixedValues;
mixedValues = [1, "Dj", true];
console.log(mixedValues);
var personObj = {};
console.log(typeof personObj);
